#!/bin/bash

. /home/demo/.bashrc
. /home/demo/rk/app/run/settings

PROBLEM=

if [ -e $APP/updating ] 
then
  exit
fi

cd $APPHOME
out=hourly.out
echo "$APPNAME hourly news" >$out
date >>$out

wget $APPURL 2>&1 | grep 'HTTP request sent' | sed 's/HTTP request sent, awaiting response... //' >hourly.out.temp
rm index.html.*

if grep -q "200 OK" hourly.out.temp
then
  echo "http test OK..." | tee -a $out
else 
  echo "PROBLEM: html error" >>$out
  cat hourly.out.temp >>$out
  PROBLEM="$PROBLEM AND html error"
fi


if grep -q "OutOfMemoryError" $APPHOME/logs/log.log
then
   echo "PROBLEM: OutOfMemoryError found" | tee -a $out
   PROBLEM="$PROBLEM AND OutOfMemoryError"
else
  echo "OutOfMemory test OK..."
fi

echo $SHELL | tee -a $out

if [[ -z $PROBLEM ]]
then
  echo "All OK..." | tee -a $out
else
  echo "PROBLEMS ARE: $PROBLEM" >>$out
  echo "." >> $out
  echo "RESTARTING..." >>$out
  DT=`date +%F-%T | sed 's/ //g'`

  mv ${APPHOME}/logs/log.log ${APPHOME}/logs/log.log.PROBLEM.$DT
  . ${APPHOME}/restart >>$out

  JPC=`ps -u $RKUSER | grep java`
  JPCNT=`ps -u $RKUSER | grep java | wc -l`
  echo $JPCNT

  if [[ $JPCNT != "1" ]]
  then
    echo "Did not restart properly... $JPC" >>$out
    echo "Did not restart properly... $JPC" | mailx -s "$APPNAME BIG PROBLEM" $EMAIL
    kill -9 `ps -u $RKUSER | grep java | sed 's/^ //' | cut -f 1 -d " " | tr '\n' " " `
    cd ${APPHOME}
    . ${APPHOME}/restart >>$out
  else
    echo "Restarted properly" >>$out
  fi

  cat $out | mailx -s "$APPNAME PROBLEM" $EMAIL

  cp $out OOPS.${out}.$DT
fi

rm $out

