#!/bin/bash

cd /home/demo/scripster/app/run
out=daily.out
echo "Scripster daily news" >$out
echo . >>$out
wget www.tryscala.com 2>&1 | grep 'HTTP request sent' | sed 's/HTTP request sent, awaiting response... //' >>$out
rm index.html.*
echo . >>$out
ps -ef | grep java >>$out
echo . >>$out
top -b -n 1 >>$out
echo . >>$out
echo "----------------------------------------------" >>$out
echo . >>$out

#wget -O /dev/null www.tryscala.org >>$out 2>&1

cat $out | mailx -s "Scripster daily news" razie@razie.com
rm $out

