/**
 * generated by Xtext 2.19.0
 */
package razie.diesel.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import razie.diesel.Nvp1RuntimeModule;
import razie.diesel.Nvp1StandaloneSetup;
import razie.diesel.ide.Nvp1IdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class Nvp1IdeSetup extends Nvp1StandaloneSetup {
  @Override
  public Injector createInjector() {
    Nvp1RuntimeModule _nvp1RuntimeModule = new Nvp1RuntimeModule();
    Nvp1IdeModule _nvp1IdeModule = new Nvp1IdeModule();
    return Guice.createInjector(Modules2.mixin(_nvp1RuntimeModule, _nvp1IdeModule));
  }
}
