/**
 * generated by Xtext 2.19.0
 */
package razie.diesel.ide;

import razie.diesel.ide.AbstractNvp1IdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class Nvp1IdeModule extends AbstractNvp1IdeModule {
}
