/**
 * generated by Xtext 2.19.0
 */
package razie.diesel.web;

import razie.diesel.web.AbstractNvp1WebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class Nvp1WebModule extends AbstractNvp1WebModule {
}
