/*
 * generated by Xtext 2.19.0
 */
package razie.diesel.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class Nvp1WebModule extends AbstractNvp1WebModule {
}
