/**
 * generated by Xtext 2.19.0
 */
package razie.diesel;

import razie.diesel.Nvp1StandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class Nvp1StandaloneSetup extends Nvp1StandaloneSetupGenerated {
  public static void doSetup() {
    new Nvp1StandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
