/**
 * generated by Xtext 2.19.0
 */
package razie.diesel;

import razie.diesel.AbstractNvp1RuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class Nvp1RuntimeModule extends AbstractNvp1RuntimeModule {
}
