/*
 * generated by Xtext 2.19.0
 */
package razie.diesel.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import razie.diesel.Nvp1RuntimeModule
import razie.diesel.Nvp1StandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class Nvp1IdeSetup extends Nvp1StandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new Nvp1RuntimeModule, new Nvp1IdeModule))
	}
	
}
