#!/bin/bash

while [ 1 -gt 0 ]; do
  echo cp -r app BACKUP/app`date --rfc-3339=seconds |sed 's/[ :]/-/g'`
  cp -r app BACKUP/app`date --rfc-3339=seconds |sed 's/[ :]/-/g'`
  echo sleeping...
  sleep 5m
done

