/*
 * generated by Xtext 2.19.0
 */
package razie.diesel.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import razie.diesel.parser.antlr.internal.InternalNvp1Parser;
import razie.diesel.services.Nvp1GrammarAccess;

public class Nvp1Parser extends AbstractAntlrParser {

	@Inject
	private Nvp1GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalNvp1Parser createParser(XtextTokenStream stream) {
		return new InternalNvp1Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public Nvp1GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Nvp1GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
