/*Generated by Xtext*/
package razdslnvp1.web.contentassist

import razdslnvp1.web.contentassist.AbstractNvp1ProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class Nvp1ProposalProvider extends AbstractNvp1ProposalProvider {
}
