/*
 * generated by Xtext 2.19.0
 */
package razie.diesel.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link Nvp1WebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractNvp1WebModule extends DefaultWebModule {

}
