/**
 * generated by Xtext 2.19.0
 */
package razie.diesel.scoping;

import razie.diesel.scoping.AbstractNvp1ScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class Nvp1ScopeProvider extends AbstractNvp1ScopeProvider {
}
