/*
 * generated by Xtext 2.19.0
 */
package razie.diesel.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractNvp1ScopeProvider extends DelegatingScopeProvider {
}
