/**
 * generated by Xtext 2.19.0
 */
package razie.diesel.validation;

import razie.diesel.validation.AbstractNvp1Validator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class Nvp1Validator extends AbstractNvp1Validator {
}
